version: '3.8'

services:
  backend:
    build:
      context: ./LearnHub_backend/learnhub-project
      dockerfile: Dockerfile
    container_name: learnhub-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://learnhub-db.cvc0o4ascyc9.ap-northeast-2.rds.amazonaws.com:3306/learnhub?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    networks:
      - learnhub-network

  frontend:
    build:
      context: ./LearnHub_frontend
      dockerfile: Dockerfile
    container_name: learnhub-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - learnhub-network

networks:
  learnhub-network:
    driver: bridge
